### ISSUE TITLE
arch config file for vlp32

### ISSUE THREAD

**Issue by amkurup** [GuoFeng-X/semantic_slam#1]
Hi,
Could you please share the arch config file used for you vlp32 model? I cant access the file from the link you have in the readme.
Thanks

**Comment by RichExplor** [comment]
Turn darknet53_ Arch in 64_ cfg.yaml Replace it

**Comment by amkurup** [comment]
Thanks for your reply. 
I would like to know the values for fov_up and fov_down. Also, how do you calculate the img_means and img_stds?

**Comment by RichExplor** [comment]
> Thanks for your reply.
> I would like to know the values for fov_up and fov_down. Also, how do you calculate the img_means and img_stds?
The arch_cfg.yaml :
 dataset:
   labels: "kitti"
   scans: "kitti"
   max_points: 150000 # max of any scan in dataset
   sensor:
     name: "HDL32"
     type: "spherical" # projective
     fov_up: 18
     fov_down: -18
     img_prop:
       width: 2048
       height: 64
     img_means: #range,x,y,z,signal
       - 9.83443
       - 0.8393
       - 0.602
       - 0.170
       - 25.5
     img_stds: #range,x,y,z,signal
       - 10.7786
       - 11.0324
       - 8.97
       - 1.50
       - 27.03

**Comment by amkurup** [comment]
Thanks!
Shouldn't the height be changes to 32? Also, how do you calculate the img_means and img_stds?

**Comment by RichExplor** [comment]
> Thanks!
> Shouldn't the height be changes to 32? Also, how do you calculate the img_means and img_stds?

Because our vlp32 is not evenly divided by angle, we set the height to 64 to display all the laser lines; the img_means and img_stds are calculated based on our own recorded data set.
